version: '3.9'
services:
  postgres:
    image: postgres:16.0
    container_name: file-service-postgres
    environment:
      POSTGRES_DB: 'database'
      POSTGRES_USER: 'angel'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '5432:5432'
    volumes:
      - .data:/var/lib/postgres
volumes:
  .data:
